drop table if exists Product_types cascade;
create table Product_types(
    id int primary key generated by default as identity,
    type_name varchar(100)
);

drop table if exists Users cascade;
create table Users(
    id int primary key generated by default as identity,
    user_name varchar(100),
    email varchar(40) 

);

drop table if exists Products cascade;
create table Products(
    id int primary key generated by default as identity,
    product_name varchar(200),
    type_id int references Product_types(id) on delete cascade,
    price numeric
);

drop table if exists Orders cascade;
create table Orders(
    id int primary key generated by default as identity,
    order_date date,
    user_id int references Users(id) on delete cascade 
);

drop table if exists Sales;
create table Sales(
    product_id int references Products(id) on delete cascade,
    order_id int references Orders(id) on delete cascade,
    amount int,
    primary key(product_id, order_id)
);

INSERT INTO product_types(type_name) VALUES('Electronics');
INSERT INTO product_types(type_name) VALUES('Clothing');
INSERT INTO product_types(type_name) VALUES('Furniture');


INSERT INTO Products (product_name, type_id, price)
VALUES
  ('Wireless Headphones', 1, 79.99),
  ('Running Shoes', 2, 49.99),
  ('Bookshelf', 3, 89.99),
  ('Digital Camera', 1, 299.99),
  ('Stainless Steel Water Bottle', 2, 14.99),
  ('Laptop', 1, 999.99),
  ('Smartphone', 1, 499.99),
  ('T-shirt', 2, 19.99),
  ('Jeans', 2, 39.99),
  ('Coffee Table', 3, 149.99);

INSERT INTO Users (user_name, email)
VALUES
  ('John Doe', 'john.doe@example.com'),
  ('Alice Smith', 'alice.smith@example.com'),
  ('Bob Johnson', 'bob.johnson@example.com'),
  ('Emma White', 'emma.white@example.com'),
  ('Charlie Brown', 'charlie.brown@example.com'),
  ('Olivia Taylor', 'olivia.taylor@example.com'),
  ('David Wilson', 'david.wilson@example.com'),
  ('Sophia Lee', 'sophia.lee@example.com'),
  ('Daniel Miller', 'daniel.miller@example.com'),
  ('Grace Davis', 'grace.davis@example.com'),
  ('Ethan Moore', 'ethan.moore@example.com'),
  ('Ava Anderson', 'ava.anderson@example.com'),
  ('Logan Wilson', 'logan.wilson@example.com'),
  ('Mia Turner', 'mia.turner@example.com'),
  ('Noah King', 'noah.king@example.com'),
  ('Isabella Scott', 'isabella.scott@example.com'),
  ('Carter Robinson', 'carter.robinson@example.com'),
  ('Sophie Evans', 'sophie.evans@example.com'),
  ('Jackson Ward', 'jackson.ward@example.com'),
  ('Lily Hughes', 'lily.hughes@example.com');

INSERT INTO Orders (order_date, user_id)
VALUES
  ('2024-01-04', 2),
  ('2024-01-03', 3),
  ('2024-01-02', 4),
  ('2024-01-01', 5),
  ('2023-12-31', 6),
  ('2023-12-30', 7),
  ('2023-12-29', 8),
  ('2023-12-28', 9),
  ('2023-12-27', 10),
  ('2023-12-26', 2),
  ('2024-01-14', 1),
  ('2024-01-13', 2),
  ('2024-01-12', 3),
  ('2024-01-11', 4),
  ('2024-01-10', 5),
  ('2024-01-09', 6),
  ('2024-01-08', 7),
  ('2024-01-07', 8),
  ('2024-01-06', 9),
  ('2024-01-05', 1),
  ('2024-01-24', 1),
  ('2024-01-23', 2),
  ('2024-01-22', 3),
  ('2024-01-21', 4),
  ('2024-01-20', 5),
  ('2024-01-19', 6),
  ('2024-01-18', 7),
  ('2024-01-17', 8),
  ('2024-01-16', 9),
  ('2024-01-15', 10);

INSERT INTO Sales (product_id, order_id, amount)
VALUES
  (1, 1, 2),
  (2, 30, 1),
  (3, 2, 3),
  (4, 3, 1),
  (5, 4, 2),
  (6, 5, 1),
  (7, 6, 4),
  (8, 7, 2),
  (9, 8, 1),
  (10, 9, 3),
  (1, 10, 2),
  (2, 11, 1),
  (3, 12, 3),
  (4, 13, 1),
  (5, 14, 2),
  (6, 15, 1),
  (7, 16, 4),
  (8, 17, 2),
  (9, 18, 1),
  (10, 19, 3),
  (1, 20, 2),
  (2, 21, 1),
  (3, 22, 3),
  (4, 23, 1),
  (5, 24, 2),
  (6, 25, 1),
  (7, 26, 4),
  (8, 27, 2),
  (9, 28, 1),
  (10, 29, 3);
 





